### ISSUE TITLE
Could you please Tag the previous Swift 1.2 Version?

### ISSUE THREAD

**Issue by winkelsdorf** [ooper-shlab/NavBar6.0-Swift#1]
see Subject, would be nice to be able to do some backward compatibility tests..

**Comment by winkelsdorf** [comment]
Probably not needed by anyone (and initial commit checkout works if needed).. Swift 2 is very close :)

**Comment by ooper-shlab** [comment]
Have tried to tag it, for practicing to use git. Tell me if you find something wrong.

**Comment by winkelsdorf** [comment]
@ooper-shlab That's always a good idea :+1: I can confirm the tag works correctly - both when downloaded via Releases and on the main via the Branch/Tag Selector creating an on-demand ZIP. Good work!

**Comment by ooper-shlab** [comment]
Thanks for telling me the feature and giving me a feedback. I'll use it for other repositories in the future.

**Comment by winkelsdorf** [comment]
You're welcome :)
